name: CI Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  lint:
    name: Code Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: false
          submodules: false

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint -r requirements.txt

      - name: Run Pylint
        run: pylint --fail-under=7.0 ./src  # Replace ./src with your actual package directory
        continue-on-error: true

      - name: Check Dockerfile line endings
        run: |
          if [ -f Dockerfile ] && grep -q $'\r' Dockerfile; then
            echo "::error::Dockerfile contains CRLF line endings. Convert to LF."
            exit 1
          fi

      - name: Run Hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
          ignored-rules: "DL3008,DL3013"

  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest  # If using pytest instead of unittest

      - name: Run tests
        run: |
          python -m pytest tests/  # If using pytest
          # or for unittest:
          # python -m unittest discover -s tests