name: CI Pipeline

on:
  push:
    branches:
      - main      # Trigger on pushes to the main branch
      - develop   # Trigger on pushes to a development branch (optional)
  pull_request:
    branches:
      - main
      - develop

jobs:
  lint:
    name: Code Linting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Use the latest stable version

      - name: Set up Python
        uses: actions/setup-python@v5  # Use the latest stable version
        with:
          python-version: '3.x'  # Use the latest stable Python 3 version

      - name: Install dependencies
        run: pip install -r requirements.txt  # Assuming you have a requirements.txt

      - name: Run Pylint
        run: pylint --fail-under=7.0 your_app_folder  # Adjust to your app's folder
        continue-on-error: true  # Allow pipeline to continue even if linting fails

      - name: Run Hadolint (Dockerfile Linter)
        uses: hadolint/hadolint-action@v3.1.0  # Use a specific stable version
        with:
          dockerfile: Dockerfile  # Specify the path to your Dockerfile

  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: lint  # This job will only run after the 'lint' job completes successfully

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run unit tests
        run: python -m unittest discover

  # Optional: Add a build job if you want to verify your Docker image builds
  # build:
  #   name: Docker Image Build
  #   runs-on: ubuntu-latest
  #   needs: test  # Build only if tests pass
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4
  #
  #     - name: Build Docker image
  #       run: docker build -t your-image-name .